yarnPath: .yarn/releases/yarn-4.1.1.cjs

nodeLinker: pnp

npmScopes:
  piktur:
    npmPublishRegistry: https://npm.pkg.github.com/piktur
    npmRegistryServer: https://npm.pkg.github.com/piktur
    npmAuthToken: "${GITHUB_TOKEN}"
